spring.application.name=DATN

#Config DB
spring.datasource.url=jdbc:postgresql://localhost:5432/DATN
spring.datasource.username=postgres
spring.datasource.password=Qnd2330@.
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=2330

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=none